### PR TITLE
Fix an issue with closures in gccgo.

### PR DESCRIPTION
**Pull request by allomov**
GCC Go frontend has a bug that caused an error from https://github.com/cloudfoundry/bosh-init/issues/34 ([bug description](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66431)). 

This PR allows you to run bosh-init deployment with this bug.

### CODE REVIEW

**Comment by allomov** [comment]
It looks like here is much the same issue:  
https://github.com/cloudfoundry/bosh-agent/commit/26fe4b08f1fb9ac6c5fbee4fcd139c1167c3c39b.

**Comment by cppforlife** [comment]
@allomov could you add a comment with a link to the gccgo bug.

**Comment by allomov** [comment]
@cppforlife sure. done.

**Comment by cppforlife** [comment]
Fixed in 0.0.54.

**Pull request closed without merging**
